[tool.poetry]
name = "pybgpranking2"
version = "2.0.1"
description = "Python CLI and module for BGP Ranking"
authors = ["Raphaël Vinot <raphael.vinot@circl.lu>"]
license = "BSD-3-Clause"

readme = "README.md"

classifiers = [
    'License :: OSI Approved :: BSD License',
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Operating System :: POSIX :: Linux',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Telecommunications Industry',
    'Intended Audience :: Information Technology',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Topic :: Security',
    'Topic :: Internet',
]

include = ['README.md']

[tool.poetry.scripts]
bgpranking = 'pybgpranking2:main'

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
Sphinx = { version = "^4.3", optional = true }
pyipasnhistory = "^2.1"

[tool.poetry.dev-dependencies]
mypy = "^0.931"
types-requests = "^2.26.0"
ipython = "^8.0.0"
pytest = "^6.2.5"

[tool.poetry.extras]
docs = ["Sphinx"]

[build-system]
requires = ["poetry_core>=1.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
